platform :ios, '14.1'
install! 'cocoapods', :share_schemes_for_development_pods => false

target 'iosApp' do
  use_frameworks!

  pod 'Shared', :path => '../shared'

  pod 'Alamofire'
  pod 'Kingfisher'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1'
      end
    end

    shared_target = installer.pods_project.targets.find { |t| t.name == 'shared' }
    if shared_target
      shared_target.build_phases.each do |phase|
        if phase.respond_to?(:name) && phase.name == '[CP-User] Build shared'
          phase.shell_script = <<~SCRIPT
            export JAVA_HOME=${JAVA_HOME:-$(/usr/libexec/java_home 2>/dev/null || echo "/Library/Java/JavaVirtualMachines/current/Contents/Home")}
            export GRADLE_OPTS="-Xmx4096M -Dfile.encoding=UTF-8"
            cd "$SRCROOT/.."
            "./gradlew" :shared:embedAndSignAppleFrameworkForXcode
          SCRIPT
        end
      end
    end
  end
end
