[versions]
agp = "8.6.0"
android-compileSdk = "35"
android-minSdk = "24"
android-targetSdk = "35"
sqlDelight = "2.1.0"
androidx-activityCompose = "1.10.1"
androidx-appcompat = "1.7.0"
androidx-constraintlayout = "2.2.1"
androidx-core-ktx = "1.15.0"
androidx-espresso-core = "3.5.1"
androidx-material = "1.12.0"
androidx-test-junit = "1.1.5"
compose-plugin = "1.6.10"
composeBom = "2025.05.00"
coroutinesVersion = "1.8.0"
hiltAndroid = "2.51.1"
junit = "4.13.2"
koinAndroidxCompose = "3.5.3"
coilCompose = "2.4.0"
koinCore = "3.2.0"
koinTest = "3.2.0"
kotlin = "2.1.10"
ktor = "3.1.0"
ksp = "2.1.10-1.0.30"
landscapistCoil3 = "2.4.7"
landscapistPlaceholder = "2.4.7"
landscapistAnimation = "2.4.7"
lifecycleVersion = "2.8.7"
material3Android = "1.3.2"
sqlDelightKMP = "2.1.0"
mockk = "1.13.12"
kotlinx-coroutines-test = "1.8.0"
ktor-client-mock = "3.1.0"
firebase-appdistribution = "5.1.1"
google-services = "4.4.2"
firebase-bom = "33.9.0"
firebase-crashlytics-plugin = "3.0.3"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlinKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
sqlDelight = { id = "app.cash.sqldelight", version.ref = "sqlDelightKMP" }
firebaseAppDistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebase-appdistribution" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-plugin" }

[libraries]
# AndroidX
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleVersion" }

# Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinCore" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koinTest" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinCore" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroidxCompose" }

# Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor-client-mock" }

# KotlinX
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutinesVersion" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }

# SQLDelight
sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqlDelightKMP" }
sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelightKMP" }
sqldelight-native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelightKMP" }

# Landscapist
landscapist-placeholder = { module = "com.github.skydoves:landscapist-placeholder", version.ref = "landscapistPlaceholder" }
landscapist-animation = { module = "com.github.skydoves:landscapist-animation", version.ref = "landscapistAnimation" }
landscapist-palette = { module = "com.github.skydoves:landscapist-palette", version.ref = "landscapistCoil3" }
landscapist-coil3 = { module = "com.github.skydoves:landscapist-coil3", version.ref = "landscapistCoil3" }

# Testing
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }